### ISSUE TITLE
Crash on invalid unicode character

### ISSUE THREAD

**Issue by adamreid** [jawerty/AlienFeed#16]
on /r/rust today there's a link entitled "Let's avoid having both foo() and foo_opt()" and it seems the apostrophe in "Let's" is raising a UnicodeEncodeError. Here's a repr of the string in question:
u'\x1b[92m 5 -> \x1b[93m23 \x1b[94mLet\u2019s avoid having both foo() and foo_opt()'

And the traceback.

Traceback (most recent call last):
  File "C:\Python27\Scripts\alienfeed-script.py", line 8, in <module>
    load_entry_point('AlienFeed==0.3.2', 'console_scripts', 'alienfeed')()
  File "C:\Python27\Scripts\alien.py", line 229, in main
    subreddit_viewer(subm_gen)
  File "C:\Python27\Scripts\alien.py", line 71, in subreddit_viewer
    links = submission_getter(generator, verbose=True)
  File "C:\Python27\Scripts\alien.py", line 117, in submission_getter
    print line
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 27: character maps to <undefined>

**Comment by eleweek** [comment]
setting environment variable `PYTHONIOENCODING` to `utf8` should fix the isssue
